
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COS DIVIDE LPAREN MINUS NUM PLUS RPAREN SIN TAN TIMES\n   expr : expr PLUS term\n        | expr MINUS term\n   \n expr : term\n \n term : term TIMES factor\n      | term DIVIDE factor\n \n    term : SIN LPAREN expr RPAREN\n         | COS LPAREN expr RPAREN\n         | TAN LPAREN expr RPAREN\n    \n term : factor\n \n    factor : NUM\n    \n factor : LPAREN expr RPAREN\n '
    
_lr_action_items = {'SIN':([0,5,9,10,13,15,16,],[4,4,4,4,4,4,4,]),'COS':([0,5,9,10,13,15,16,],[6,6,6,6,6,6,6,]),'TAN':([0,5,9,10,13,15,16,],[7,7,7,7,7,7,7,]),'NUM':([0,5,9,10,11,12,13,15,16,],[8,8,8,8,8,8,8,8,8,]),'LPAREN':([0,4,5,6,7,9,10,11,12,13,15,16,],[5,13,5,15,16,5,5,5,5,5,5,5,]),'$end':([1,2,3,8,17,18,19,20,22,25,26,27,],[0,-3,-9,-10,-1,-2,-4,-5,-11,-6,-7,-8,]),'PLUS':([1,2,3,8,14,17,18,19,20,21,22,23,24,25,26,27,],[9,-3,-9,-10,9,-1,-2,-4,-5,9,-11,9,9,-6,-7,-8,]),'MINUS':([1,2,3,8,14,17,18,19,20,21,22,23,24,25,26,27,],[10,-3,-9,-10,10,-1,-2,-4,-5,10,-11,10,10,-6,-7,-8,]),'RPAREN':([2,3,8,14,17,18,19,20,21,22,23,24,25,26,27,],[-3,-9,-10,22,-1,-2,-4,-5,25,-11,26,27,-6,-7,-8,]),'TIMES':([2,3,8,17,18,19,20,22,25,26,27,],[11,-9,-10,11,11,-4,-5,-11,-6,-7,-8,]),'DIVIDE':([2,3,8,17,18,19,20,22,25,26,27,],[12,-9,-10,12,12,-4,-5,-11,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,5,13,15,16,],[1,14,21,23,24,]),'term':([0,5,9,10,13,15,16,],[2,2,17,18,2,2,2,]),'factor':([0,5,9,10,11,12,13,15,16,],[3,3,3,3,19,20,3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expr','test.py',62),
  ('expr -> expr MINUS term','expr',3,'p_expr','test.py',63),
  ('expr -> term','expr',1,'p_expr_term','test.py',72),
  ('term -> term TIMES factor','term',3,'p_term','test.py',78),
  ('term -> term DIVIDE factor','term',3,'p_term','test.py',79),
  ('term -> SIN LPAREN expr RPAREN','term',4,'p_func','test.py',88),
  ('term -> COS LPAREN expr RPAREN','term',4,'p_func','test.py',89),
  ('term -> TAN LPAREN expr RPAREN','term',4,'p_func','test.py',90),
  ('term -> factor','term',1,'p_term_factor','test.py',104),
  ('factor -> NUM','factor',1,'p_factor','test.py',110),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor_group','test.py',116),
]
